name: Convert Resumes and CVs to PDF

on:
    push:
        paths:
            - 'ResumeAndCV/**'
        branches:
            - main  # or any branch you want this action to run on
    pull_request:
        paths:
            - 'ResumeAndCV/**'
        branches:
            - main  # or any branch you want this action to run on
    workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
    convert-general-resume:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                python-version: '3.10'

            - name: Install pandoc and dependencies
              run: |
                    sudo apt-get update
                    sudo apt-get install -y pandoc texlive

            - name: Convert Markdown to PDF
              run: |
                  pandoc ResumeAndCV/resume.md \
                  -V geometry:margin=0.75in \
                  -o ResumeAndCV/Resume.pdf

            - name: Upload Resume PDF
              uses: actions/upload-artifact@v6
              with:
                name: Resume
                path: ResumeAndCV/Resume.pdf
    convert-power-resume:
        runs-on: ubuntu-latest
        needs: convert-general-resume
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Install pandoc and LaTeX
              run: |
                  sudo apt-get update
                  sudo apt-get install -y pandoc texlive

            - name: Build power resume
              run: |
                  pandoc ResumeAndCV/power_resume.md \
                    -V geometry:margin=0.75in \
                    -o ResumeAndCV/Resume-Power.pdf

            - name: Upload power resume
              uses: actions/upload-artifact@v6
              with:
                  name: Resume-Power
                  path: ResumeAndCV/Resume-Power.pdf
    convert-cv:
        runs-on: ubuntu-latest
        needs: convert-general-resume
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Install pandoc and LaTeX
              run: |
                  sudo apt-get update
                  sudo apt-get install -y pandoc texlive

            - name: Build CV
              run: |
                  pandoc ResumeAndCV/cv.md \
                    -V geometry:margin=0.75in \
                    -o ResumeAndCV/CV.pdf

            - name: Upload CV
              uses: actions/upload-artifact@v6
              with:
                  name: CV
                  path: ResumeAndCV/CV.pdf